config/routes.rb
Rails.application.routes.draw do
  # resources :posts
  resources :upls
  resources :posts do 
    resources :comments

  end
  resources :projects do
    resources :tasks
    resources :upls
    resources :posts do 
    resources :comments
  end
  end
  resources :tasks

  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
      
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)
    @tasks = @project.tasks

    if @task.save
      redirect_to new_project_task_path
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to new_project_task_path
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
      @task.destroy
          redirect_to new_project_task_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="div_edit_task">
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit "Edit", class: "btn btn-primary"%>
    <%= link_to "Back", :back, class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_project_task_path  class: "project-attach"%>

app/views/tasks/new.html.erb
<%= form_for([@task.project, @task]) do |f| %>


<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h4 class="text-center my-3 pb-3">To Do App</h4>

            <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <div class="col-12">
                <div class="form-outline">
                  <%= f.text_area :name, class:"form-control", id: "form1" %>
                  <label class="form-label" for="form1">Enter a task here</label>
                
                </div>
              </div>

              <div class="col-12">
                <%= f.submit "Creat Task", class:"btn btn-primary"%><%= link_to "Back", project_path(@project), class: "btn btn-primary"%>
                
              </div>
            </form>
              <% end %>
            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Id</th>
                  <th scope="col">Name</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @tasks.each do |task| %>
                <% if task.persisted? %>
                <tr>
                  <th scope="row"><%= task.id %></th>
                  <td><%= task.name %></td>
                  <td>
                    <%= link_to 'Destroy', [task.project, task], 'data-turbo-method': :delete, class:"btn btn-danger" %>
                    <%= link_to 'Edit', edit_project_task_path(task.project, task), class: "btn btn-success ms-1"  %>
                    
                  </td>
                </tr>
                <% end %>
                <% end %>

              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>