config/routes.rb
Rails.application.routes.draw do
  # resources :posts
  resources :upls
  resources :posts do 
    resources :comments

  end
  resources :projects do
    resources :tasks
    resources :upls
    resources :posts do 
    resources :comments
  end
  end
  resources :tasks

  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/upl.rb
class Upl < ApplicationRecord
  belongs_to :project
  has_one_attached :upler
end

app/controllers/upls_controller.rb
class UplsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_upl, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @upls = @project.upls
  end

  # GET projects/1/tasks/1
  def show
      
  end

  # GET projects/1/tasks/new
  def new
    @upl = @project.upls.build
    @upls = @project.upls
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @upl = @project.upls.build(upl_params)

    if @upl.save
      redirect_to new_project_upl_path
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @upl.update(upl_params)
      redirect_to new_project_upl_path
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
      @upl.destroy
          redirect_to new_project_upl_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_upl
      @upl = @project.upls.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def upl_params
      params.require(:upl).permit(:name, :upler)
    end
end

app/helpers/upls_helper.rb
module UplsHelper
end

app/views/upls/_form.html.erb
<div class="div_edit_upl">
<%= form_for([@upl.project, @upl]) do |f| %>
  <% if @upl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upl.errors.count, "error") %> prohibited this upl from being saved:</h2>

      <ul>
      <% @upl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
  <%= f.label :upler %><br />
  <%= f.file_field :upler %>
</div>
  <div class="actions">
    <%= f.submit "Edit", class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/upls/_upl.html.erb
<div id="<%= dom_id upl %>">
  <p>
    <strong>Name:</strong>
    <%= upl.name %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= upl.project_id %>
  </p>

</div>

app/views/upls/edit.html.erb
<h1>Editing upl</h1>

<%= render "form", upl: @upl %>
<%= link_to "Back", :back, class: "btn btn-primary"%>

app/views/upls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Upls</h1>

<div id="upls">
  <% @upls.each do |upl| %>
    <%= render upl %>
    <p>
      <%= link_to "Show this upl", upl %>
    </p>
  <% end %>
</div>

<%= link_to "New upl", new_upl_path %>

app/views/upls/new.html.erb
<%= form_for([@upl.project, @upl]) do |f| %>
  <% if @upl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upl.errors.count, "error") %> prohibited this upl from being saved:</h2>

      <ul>
      <% @upl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h4 class="text-center my-3 pb-3">To Do App</h4>

            <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <div class="col-12">
                <div class="form-outline">
                <%= f.file_field :upler, class:"form-control", id: "form1" %>
                  <%= f.text_area :name, class:"form-control", id: "form1" %>
                  <label class="form-label" for="form1">Enter a upl here</label>
                </div>
              </div>

              <div class="col-12">
                <%= f.submit "Creat upl", class:"btn btn-primary"%><%= link_to "Back", project_path(@project), class: "btn btn-primary"%>

                
              </div>
            </form>
              <% end %>
            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Id</th>
                  <th scope="col">Name</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @upls.each do |upl| %>
                  <% if upl.upler.attached? %>
                <% if upl.persisted? %>
                <tr>
                  <th scope="row"><%= upl.id %></th>
                  <td><%= upl.name %></td>

                  <% if  upl.upler.image?%>
                  <td><a href="#"><%= link_to image_tag(upl.upler, class: "img_upload"),  rails_blob_path(upl.upler, disposition: "attachment") %>
                  <% elsif upl.upler.audio? %>
                  <td>
                  <a href="#"><%= upl.upler.filename %>
                  <audio controls>
                   <source src=" <%= rails_blob_url(upl.upler, disposition: "attachment") %>" type="audio/mpeg"/>
                   </audio></a>
                   </td>
                  <% else %>
                  <td>
                  <%= link_to upl.upler.filename,  rails_blob_path(upl.upler, disposition: "attachment") %>
                  </td>
                  <% end %>

                  <td>
                    <%= link_to 'Destroy', [upl.project, upl], 'data-turbo-method': :delete, class:"btn btn-danger" %>
                    <%= link_to 'Edit', edit_project_upl_path(upl.project, upl), class: "btn btn-success ms-1"  %>
                  </td>
                </tr>
                <%end%>
                <% end %>
                <% end %>

              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/upls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @upl %>

<div>
  <%= link_to "Edit this upl", edit_upl_path(@upl) %> |
  <%= link_to "Back to upls", upls_path %>

  <%= button_to "Destroy this upl", @upl, method: :delete %>
</div>