config/routes.rb
Rails.application.routes.draw do
  # resources :posts
  resources :upls
  resources :posts do 
    resources :comments

  end
  resources :projects do
    resources :tasks
    resources :upls
    resources :posts do 
    resources :comments
  end
  end
  resources :tasks

  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true

  has_many :tasks, dependent: :destroy
  has_many :upls, dependent: :destroy
  has_many :posts, dependent: :destroy

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    if @project.user != current_user
      redirect_to root_path
    end
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project) do |form| %>
  <% if @project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize( @project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Name this project:</label>
            <%= form.text_field :name, class:"form-control" %>
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Description:</label>
                <%= form.text_area :description, class:"form-control" %>
                  <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>

          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light border border-success p-2 mb-2 border-opacity-75 text-light bg-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit class:"btn btn-success" %>

      </div>
    </div>
  </div>
</div>
  <div>
  </div>


<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1 class="h1-project">Projects</h1>

<%= stylesheet_link_tag "register" %>
<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>
<%= link_to "sign out", new_user_session_path %>

app/views/projects/new.html.erb
<h1>New project</h1>


<%= render "form", project: @project %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>


<br>
 <%= link_to "Back", root_path, class: "back"%>

app/views/projects/show.html.erb
<%= render 'form' %>
<div class="peo">
<div class="project-name"><h1><%= @project.name %></h1></div>
    <div class="edit-delete">
      <button type="button"  data-bs-toggle="modal" data-bs-target="#exampleModal"  class="project-edit">Edit Project</button>
      <%= button_to "Destroy this project", @project, method: :delete , class:"project-delete bg-danger"  %> 

      <p><%= link_to "Attachment", new_project_upl_path(@project), class: "project-attach bg-info"  %></p> <br />
      <p><%= link_to "Posts", project_posts_path(@project), class: "project-attach bg-light" %></p> <br />
      <p><%= link_to "Tasks", new_project_task_path(@project), class: "project-tasks bg-warning" %></p>
      <%= link_to "Back", root_path , class: "back1"%>
      
      


    </div>
   
</div>