config/routes.rb
Rails.application.routes.draw do
  # resources :posts
  resources :upls
  resources :posts do 
    resources :comments

  end
  resources :projects do
    resources :tasks
    resources :upls
    resources :posts do 
    resources :comments
  end
  end
  resources :tasks

  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @project = Project.find(params[:project_id])
    @posts = @project.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    @pr = @post.project.id

  end

  # GET /posts/new
  def new
    @project = Project.find(params[:project_id])
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @project = Project.find(params[:project_id])
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @pr = @post.project.id
    @post.destroy

    respond_to do |format|
      format.html { redirect_to project_posts_path(@pr), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :project_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit_form.html.erb
<%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
  
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>
  
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.text_field :project_id, value: @project.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>


</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "edit_form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post, class: "show-btn" %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_project_post_path(@project), class: "show-btn1" %>
<%= link_to "Back", root_path, class: "back-post"%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", project_posts_path(@project), class: "edit-btn" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <% if @post.project.user.id == current_user.id %>
<%= link_to "Edit this post", edit_post_path(@post), class: "edit-btn" %> |
  <%= link_to "Back to posts", project_posts_path(@pr), class: "back-btn"   %>

  <%= button_to "Destroy this post", @post, method: :delete, class: "back-post1"%>
  <% else %>
  <%= link_to "Back to posts", project_posts_path(@pr), class: "project-attach" %>
  <% end %>

  </div>


<div class="container">
  <%= render 'comments/form', 
    post: @post, 
    comment: @post.comments.build,
    submit_label: "Comment" %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
    post: @post, 
    comment: comment %>
  <% end %>
</div>